"""
Agent 2 – Script Writer (Horoscope Mode)
Reads the horoscope JSON from content_pieces.trend_topic (generated by Agent 1)
and turns it into a structured TikTok video script with DALL-E image prompts.
"""
import json
import logging
from typing import Optional

import anthropic

from config import settings
from supabase_client import get_client, get_config, log

logger = logging.getLogger(__name__)

SCRIPT_SCHEMA = """{
  "hook": "<5-sekündiger Eröffnungssatz der sofort fesselt, mit Sternzeichen-Symbol>",
  "segments": [
    {
      "text": "<gesprochener Text für dieses Segment, auf Deutsch>",
      "image_prompt": "<DALL-E 3 Bildprompt, mystisch, Hochformat 9:16, cinematic>",
      "duration_s": <ganze Zahl Sekunden, 5-12>
    }
  ],
  "cta": "<Abschluss-Call-to-Action auf Deutsch, z.B. 'Folge für tägliche Horoskope!'>",
  "hashtags": ["#Horoskop", "#Steinbock", "#Tageshoroskop", "#Astrologie"],
  "total_duration_s": <Summe aller Segment-Dauern>
}"""

ZODIAC_EMOJIS = {
    "Widder": "♈", "Stier": "♉", "Zwillinge": "♊", "Krebs": "♋",
    "Löwe": "♌", "Jungfrau": "♍", "Waage": "♎", "Skorpion": "♏",
    "Schütze": "♐", "Steinbock": "♑", "Wassermann": "♒", "Fische": "♓",
}


def run(run_id: str, content_id: Optional[int] = None) -> int:
    sb = get_client()

    if content_id:
        result = sb.table("content_pieces").select("*").eq("id", content_id).eq("status", "TREND_SCORED").single().execute()
    else:
        result = sb.table("content_pieces").select("*").eq("status", "TREND_SCORED").order("trend_score", desc=True).limit(1).execute()
        result.data = result.data[:1]

    if not result.data:
        log("script_writer", run_id, "warning", "Kein TREND_SCORED ContentPiece gefunden, überspringe")
        return -1

    piece = result.data[0]

    # Parse horoscope JSON from trend_topic
    try:
        horoscope = json.loads(piece["trend_topic"])
    except (json.JSONDecodeError, TypeError):
        horoscope = {"general": piece["trend_topic"]}

    zodiac = horoscope.get("zodiac") or get_config("zodiac_sign", "Steinbock")
    target_date = horoscope.get("date") or get_config("horoscope_date", "heute")
    emoji = ZODIAC_EMOJIS.get(zodiac, "⭐")

    log("script_writer", run_id, "info",
        f"Erstelle Video-Script für {emoji} {zodiac} – {target_date} (Piece #{piece['id']})")

    horoscope_summary = (
        f"Allgemein: {horoscope.get('general', '')}\n"
        f"Liebe: {horoscope.get('love', '')}\n"
        f"Karriere: {horoscope.get('career', '')}\n"
        f"Energie: {horoscope.get('energy_level', 8)}/10\n"
        f"Glückszahl: {horoscope.get('lucky_number', '?')}\n"
        f"Glücksfarbe: {horoscope.get('lucky_color', '?')}\n"
        f"Planetarischer Einfluss: {horoscope.get('planetary_influence', '')}\n"
        f"Affirmation: {horoscope.get('affirmation', '')}"
    )

    client = anthropic.Anthropic(api_key=settings.anthropic_api_key)
    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=3000,
        system=(
            "Du bist ein erfahrener Astrologe und viraler TikTok-Creator. "
            "Du verwandelst Horoskop-Inhalte in mitreißende Kurzvideos auf Deutsch. "
            "Dein Stil ist mystisch, warm und inspirierend. "
            "Antworte ausschließlich mit validem JSON, kein Markdown."
        ),
        messages=[{
            "role": "user",
            "content": (
                f"Erstelle ein TikTok-Video-Script (45-60 Sekunden, 5-6 Segmente) basierend auf:\n\n"
                f"Sternzeichen: {emoji} {zodiac}\n"
                f"Datum: {target_date}\n\n"
                f"Horoskop-Inhalt:\n{horoscope_summary}\n\n"
                f"Aufbau:\n"
                f"1. Hook: Fesselnder Einstieg mit '{emoji} {zodiac}!'\n"
                f"2. Tagesenergie (allgemein)\n"
                f"3. Liebe & Beziehungen\n"
                f"4. Karriere & Finanzen\n"
                f"5. Glückszahl {horoscope.get('lucky_number', '?')} & Glücksfarbe {horoscope.get('lucky_color', '?')}\n"
                f"6. Affirmation als Abschluss\n\n"
                f"Jedes Segment braucht einen mystischen DALL-E Bildprompt (Hochformat 9:16, "
                f"Astrologie-Ästhetik, cosmic/mystical, kein Text im Bild).\n\n"
                f"Antworte NUR mit diesem JSON-Schema:\n{SCRIPT_SCHEMA}"
            ),
        }],
    )

    raw = response.content[0].text.strip()
    script_data = json.loads(raw)
    assert "hook" in script_data and "segments" in script_data and len(script_data["segments"]) > 0

    sb.table("content_pieces").update({
        "script": json.dumps(script_data, ensure_ascii=False),
        "status": "SCRIPT_READY",
    }).eq("id", piece["id"]).execute()

    segment_count = len(script_data["segments"])
    duration = script_data.get("total_duration_s", "?")
    log("script_writer", run_id, "info",
        f"Script fertig für #{piece['id']}: {segment_count} Segmente, ~{duration}s")
    return piece["id"]
